# Generated by Django 5.0.6 on 2024-06-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('present_qualification', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('parents_phone_number', models.CharField(max_length=15)),
                ('computer_course', models.CharField(choices=[('CFB', 'Computer for Beginner'), ('DCO', 'Diploma in Computer Operator'), ('DGD', 'Diploma in Graphic Design'), ('OP', 'Office Package'), ('WD', 'Webpage Designing'), ('CH', 'Computer Hardware'), ('P', 'Programming')], max_length=3)),
                ('language_course', models.CharField(choices=[('KR', 'Korean'), ('EN', 'English'), ('JP', 'Japanese'), ('HE', 'Hebrew'), ('TU', 'Tuition')], max_length=2)),
                ('course_level', models.CharField(choices=[('B', 'Basic'), ('I', 'Intermediate'), ('A', 'Advance')], max_length=1)),
            ],
        ),
    ]
